namespace WebApp.Payloads.DocumentPayload;

public class DocumentBctc200Payload : BaseDocumentPayload
{
    public ChiTieuChinhNamNay_200? ChiTieuChinhNamNay { get; set; }
    public Pl_KqkdNamNay_200? KqkdNamNay { get; set; }
}

public class ChiTieuChinhNamNay_200
{
    public string? ct100 { get; set; }
    public string? ct110 { get; set; }
    public string? ct111 { get; set; }
    public string? ct112 { get; set; }
    public string? ct120 { get; set; }
    public string? ct121 { get; set; }
    public string? ct122 { get; set; }
    public string? ct123 { get; set; }
    public string? ct130 { get; set; }
    public string? ct131 { get; set; }
    public string? ct132 { get; set; }
    public string? ct133 { get; set; }
    public string? ct134 { get; set; }
    public string? ct135 { get; set; }
    public string? ct136 { get; set; }
    public string? ct137 { get; set; }
    public string? ct139 { get; set; }
    public string? ct140 { get; set; }
    public string? ct141 { get; set; }
    public string? ct149 { get; set; }
    public string? ct150 { get; set; }
    public string? ct151 { get; set; }
    public string? ct152 { get; set; }
    public string? ct153 { get; set; }
    public string? ct154 { get; set; }
    public string? ct155 { get; set; }
    public string? ct200 { get; set; }
    public string? ct210 { get; set; }
    public string? ct211 { get; set; }
    public string? ct212 { get; set; }
    public string? ct213 { get; set; }
    public string? ct214 { get; set; }
    public string? ct215 { get; set; }
    public string? ct216 { get; set; }
    public string? ct219 { get; set; }
    public string? ct220 { get; set; }
    public string? ct221 { get; set; }
    public string? ct222 { get; set; }
    public string? ct223 { get; set; }
    public string? ct224 { get; set; }
    public string? ct225 { get; set; }
    public string? ct226 { get; set; }
    public string? ct227 { get; set; }
    public string? ct228 { get; set; }
    public string? ct229 { get; set; }
    public string? ct230 { get; set; }
    public string? ct231 { get; set; }
    public string? ct232 { get; set; }
    public string? ct240 { get; set; }
    public string? ct241 { get; set; }
    public string? ct242 { get; set; }
    public string? ct250 { get; set; }
    public string? ct251 { get; set; }
    public string? ct252 { get; set; }
    public string? ct253 { get; set; }
    public string? ct254 { get; set; }
    public string? ct255 { get; set; }
    public string? ct260 { get; set; }
    public string? ct261 { get; set; }
    public string? ct262 { get; set; }
    public string? ct263 { get; set; }
    public string? ct268 { get; set; }
    public string? ct270 { get; set; }
    public string? ct300 { get; set; }
    public string? ct310 { get; set; }
    public string? ct311 { get; set; }
    public string? ct312 { get; set; }
    public string? ct313 { get; set; }
    public string? ct314 { get; set; }
    public string? ct315 { get; set; }
    public string? ct316 { get; set; }
    public string? ct317 { get; set; }
    public string? ct318 { get; set; }
    public string? ct319 { get; set; }
    public string? ct320 { get; set; }
    public string? ct321 { get; set; }
    public string? ct322 { get; set; }
    public string? ct323 { get; set; }
    public string? ct324 { get; set; }
    public string? ct330 { get; set; }
    public string? ct331 { get; set; }
    public string? ct332 { get; set; }
    public string? ct333 { get; set; }
    public string? ct334 { get; set; }
    public string? ct335 { get; set; }
    public string? ct336 { get; set; }
    public string? ct337 { get; set; }
    public string? ct338 { get; set; }
    public string? ct339 { get; set; }
    public string? ct340 { get; set; }
    public string? ct341 { get; set; }
    public string? ct342 { get; set; }
    public string? ct343 { get; set; }
    public string? ct400 { get; set; }
    public string? ct410 { get; set; }
    public string? ct411 { get; set; }
    public string? ct411a { get; set; }
    public string? ct411b { get; set; }
    public string? ct412 { get; set; }
    public string? ct413 { get; set; }
    public string? ct414 { get; set; }
    public string? ct415 { get; set; }
    public string? ct416 { get; set; }
    public string? ct417 { get; set; }
    public string? ct418 { get; set; }
    public string? ct419 { get; set; }
    public string? ct420 { get; set; }
    public string? ct421 { get; set; }
    public string? ct421a { get; set; }
    public string? ct421b { get; set; }
    public string? ct422 { get; set; }
    public string? ct430 { get; set; }
    public string? ct431 { get; set; }
    public string? ct432 { get; set; }
    public string? ct440 { get; set; }
}

public class Pl_KqkdNamNay_200
{
    public string? ct01 { get; set; }
    public string? ct02 { get; set; }
    public string? ct10 { get; set; }
    public string? ct11 { get; set; }
    public string? ct20 { get; set; }
    public string? ct21 { get; set; }
    public string? ct22 { get; set; }
    public string? ct23 { get; set; }
    public string? ct25 { get; set; }
    public string? ct26 { get; set; }
    public string? ct30 { get; set; }
    public string? ct31 { get; set; }
    public string? ct32 { get; set; }
    public string? ct40 { get; set; }
    public string? ct50 { get; set; }
    public string? ct51 { get; set; }
    public string? ct52 { get; set; }
    public string? ct60 { get; set; }
    public string? ct70 { get; set; }
    public string? ct71 { get; set; }
}